# Generated by Django 4.2.7 on 2025-09-15 20:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name (e.g., Computer Science)', max_length=200)),
                ('code', models.CharField(help_text='Department code (e.g., CS)', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Department description')),
                ('established_date', models.DateField(help_text='Date when department was established')),
                ('contact_email', models.EmailField(help_text='Department contact email', max_length=254)),
                ('contact_phone', models.CharField(help_text='Department contact phone', max_length=20)),
                ('location', models.CharField(help_text='Building/Floor information', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether department is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_of_department', models.ForeignKey(blank=True, help_text='Head of Department (must be faculty)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Semester name (e.g., Fall 2024)', max_length=100)),
                ('code', models.CharField(help_text='Semester code (e.g., FA24)', max_length=20, unique=True)),
                ('start_date', models.DateField(help_text='Semester start date')),
                ('end_date', models.DateField(help_text='Semester end date')),
                ('registration_start', models.DateTimeField(help_text='Registration start date and time')),
                ('registration_end', models.DateTimeField(help_text='Registration end date and time')),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current semester')),
                ('is_active', models.BooleanField(default=True, help_text='Whether semester is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['code'], name='academics_s_code_4c0d24_idx'), models.Index(fields=['is_current'], name='academics_s_is_curr_c34375_idx'), models.Index(fields=['start_date', 'end_date'], name='academics_s_start_d_68f58c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Program name (e.g., Bachelor of Computer Science)', max_length=200)),
                ('code', models.CharField(help_text='Program code (e.g., BCS)', max_length=20, unique=True)),
                ('degree_type', models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PhD'), ('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma')], help_text='Type of degree', max_length=20)),
                ('duration_years', models.PositiveIntegerField(help_text='Program duration in years', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('total_credit_hours', models.PositiveIntegerField(help_text='Total credit hours required', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('description', models.TextField(help_text='Program description')),
                ('admission_requirements', models.TextField(help_text='Admission requirements')),
                ('is_active', models.BooleanField(default=True, help_text='Whether program is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.department')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['department', 'name'],
                'indexes': [models.Index(fields=['code'], name='academics_p_code_b3fb49_idx'), models.Index(fields=['department', 'is_active'], name='academics_p_departm_ba56a3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='academics_d_code_791f98_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='academics_d_is_acti_3e204e_idx'),
        ),
    ]
